# Changelog Preview workflow
# Shows how PRs will appear in the changelog
# https://getsentry.github.io/craft/

name: Changelog Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

jobs:
  changelog-preview:
    name: Preview Changelog
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@v2
    secrets: inherit

