# Changelog Preview workflow
# Shows how PRs will appear in the changelog
# https://getsentry.github.io/craft/

name: Changelog Preview
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

jobs:
  changelog-preview:
    name: Preview Changelog
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@1c58bfd57bfd6a967b6f3fc92bead2c42ee698ce
    secrets: inherit
